### ISSUE TITLE
After installation I get error Cannot use object of type Illuminate\Http\Response as array

### ISSUE THREAD

**Issue by freeyland** [fytinnovations/oc-helpdesk#18]
After install of the plugin on my existing website I get error when clicking helpdesk button:

Cannot use object of type Illuminate\Http\Response as array
/home/steven/domains/flowtech.be/public_html/modules/backend/classes/BackendController.php line 163

? Response::make(View::make('backend::no_database'), 200)
                : $this->passToCmsController($url);
        }
  
        $controllerRequest = $this->getRequestedController($url);
        if (!is_null($controllerRequest)) {
            return $controllerRequest['controller']->run(
                $controllerRequest['action'],
                $controllerRequest['params']
            );
        }

**Comment by 4nik3t** [comment]
@freeyland Have you installed the rainlab.user and rainlab.translate plugin. if not get those plugins installed and try again

**Comment by freeyland** [comment]
Thanx, translate plugin was missing

**Comment by 4nik3t** [comment]
Glad to know @freeyland
