### ISSUE TITLE
Form is submitted twice

### ISSUE THREAD

**Issue by freeyland** [fytinnovations/oc-helpdesk#19]
When I add a comment; the comment is submitted twice. You also see twice the content

**Comment by 4nik3t** [comment]
@freeyland Are you experiencing this in the backend or in the frontend

**Comment by freeyland** [comment]
In the front-end

**Comment by 4nik3t** [comment]
Alright I will try reproducing the issue and get back to you.

**Comment by 4nik3t** [comment]
I tried to reproduce this but it works on my end. Could you please let me know how to reproduce this.

**Comment by freeyland** [comment]
On an existing ticket i am adding a comment: hh

Frederick Eyland 1 second ago
hh

Frederick Eyland 1 second ago
hh

**Comment by 4nik3t** [comment]
Have you done any changes in the component markup via overriding it?

**Comment by freeyland** [comment]
No, I did not. I'll try to reupload the code

**Comment by freeyland** [comment]
I've reuploaded the full plugin. Still the same issue.
Also the email is send twice

**Comment by freeyland** [comment]
Hey, i found the problem. WHen disable _OctoberCMS Javascript Framework_ in the settings it is not submitted twice. Very strange that the framework is loaded twice.

**Comment by freeyland** [comment]
Ok, this is a setting from my theme, so not really something to do with helpdesk.

**Comment by 4nik3t** [comment]
@freeyland Thanks for informing
