### ISSUE TITLE
Possibility to change requester in the backend

### ISSUE THREAD

**Issue by freeyland** [fytinnovations/oc-helpdesk#21]
Would be nice if in the backend you can change the requester name when creating a ticket in the backend. If someone for example gives a call for support I want to be able to create a ticket in the name of someone else in the BE.

**Comment by 4nik3t** [comment]
@freeyland Thanks for the suggestion we will update soon on the same

**Comment by 4nik3t** [comment]
@freeyland  We have added this as a option in the latest release. Please check

**Comment by aniket-magadum** [comment]
Feature has been added
