### ISSUE TITLE
Ticket Details Component not working

### ISSUE THREAD

**Issue by fldesigns** [fytinnovations/oc-helpdesk#27]
Hello, Ticket Detail not working:

Trying to get property 'conversation' of non-object

/www/htdocs/w018e2aa/beta.fldesigns.de/plugins/fytinnovations/helpdesk/components/TicketDetails.php line 112

        $this->ticket = Ticket::with('non_private_comments')->where([
            'id' => $id,
            'createable_id' => Auth::getUser()->id,
            'createable_type' => User::class
        ])->first();
  
        $this->conversation = $this->ticket->conversation;
    }
  
  
    public function onComment()
    {
        $comment = $this->ticket->comments()->create([

*** ANY IDEA ***

**Comment by aniket-magadum** [comment]
@fldesigns Could you please provide with the steps to reproduce the issue

**Comment by fldesigns** [comment]
Hi. Is used a custom and Demo design as well. It did not work on both. I’m using rainlab user for login. Created a page with ticket form and created a page for ticket details. Every time I call the detail page I receive this error

**Comment by fldesigns** [comment]
Of course user is logged in

**Comment by aniket-magadum** [comment]
@fldesigns Thanks for the info. I will get back on this tomorrow morning.

**Comment by fldesigns** [comment]
Okay - thanks. If you need further information feel free to get in touch

**Comment by aniket-magadum** [comment]
@fldesigns  Could you please update the plugin and let us know if it works now.

**Comment by fldesigns** [comment]
Hey. Now I get a Page not found error if I call the page where I put the component.

**Comment by aniket-magadum** [comment]
You would be able to access tickets only which you have created. Create a ticket using the ticket form component. and then view the ticket details component bypassing the ticket_id

**Comment by fldesigns** [comment]
Hi. I have a page for submission and ticketlist. One page for ticket details. If I creat a ticket it will be shown in ticketlist table. If I click on the link I receive page not found. Link for details is set to the correct page

**Comment by fldesigns** [comment]
Maybe my workflow is wrong?
- page for submission form
- page for list of tickets table
- page for ticket details

Page ticketlist links to detail is set to page ticket details. Is there :slug or :page? Needed? Both did not work

**Comment by fldesigns** [comment]
Oh it is :ticket_id - I’m so sorry
