### ISSUE TITLE
Get error when user not log in and go to ticket url

### ISSUE THREAD

**Issue by Webjam007** [fytinnovations/oc-helpdesk#29]
**Describe the bug**
I get an error but expect a page 404

**To Reproduce**
1. Be unlogged
1. Go to 'https://webjam.com.ua/en/ticket/12' 
(12 is a ticket number)
2. See error (If user log in there are no error)

**Expected behavior**
If user not log in and go to url like that: https://webjam.com.ua/en/ticket/(ticket number) he must get page 404.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/76408512/107278795-e700ee00-6a5e-11eb-94a3-54bd025bfa7b.jpg)

**System Information (please complete the following information):**
 - OS : Windows 10
 - Browser : chrome
 - OctoberCMS Build :  471
 - PHP version : 7.3
-  mysql version : 5.7.16

**Additional context**
It work well here: https://webjam.com.ua/en/ticket

**Comment by WARHORSE-PRO** [comment]
@Webjam007 I will look into it and let you know soon.

Thank you for your patience.

**Comment by aniket-magadum** [comment]
@Webjam007 we have fixed this in the latest release of the plugin. Please update.

**Comment by Webjam007** [comment]
Just i updated to ver.2.0.1.
If I am not login and goes to 'https://webjam.com.ua/en/ticket/12 get error again.

When I am login and and goes to 'https://webjam.com.ua/en/ticket/12 i get page 404

I expect get page 404 if i Not Loged.
Fix it, please

**Comment by aniket-magadum** [comment]
@Webjam007 could you please update the helpdesk plugin to the latest version and confirm if it's working

**Comment by Webjam007** [comment]
I updated to ver.2.0.2
Now, all works as I expected.
Thank you a lot!
