### ISSUE TITLE
Login page is not working on demo website

### ISSUE THREAD

**Issue by chrisvidal** [fytinnovations/oc-helpdesk#30]
**Describe the bug**
Login page is not working on demo website

**To Reproduce**
1. Go to 'https://ocmsdemo.fytinnovations.com/'
2. Click on 'Login/Signup'

**Comment by chrisvidal** [comment]
Page not found
We're sorry, but the page you requested cannot be found.

**Comment by aniket-magadum** [comment]
@chrisvidal Thanks for the report we will look into it

**Comment by aniket-magadum** [comment]
@chrisvidal The issue has been fixed
